AWSTemplateFormatVersion: '2010-09-09'

Resources:

  # S3 Bucket for data
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: proy-datos-martin-solano

  # S3 Bucket for code
  CodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: proy-codigos-martin-solano

  # DynamoDB Table
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ProyDatosPipeline
      AttributeDefinitions:
        - AttributeName: MesAnyo
          AttributeType: S
        - AttributeName: Fecha
          AttributeType: S
      KeySchema:
        - AttributeName: MesAnyo
          KeyType: HASH
        - AttributeName: Fecha
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES  # Ensure stream is enabled

  # SNS Topic for Alarm Notifications
  TemperatureAlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: proy-alarma-temperatura

  # SNS Subscription for Alarm Notifications
  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: jlabellan@um.es
      TopicArn: !Ref TemperatureAlarmTopic

Outputs:

  # Output the name of the DataBucket
  DataBucketName:
    Value: !Ref DataBucket
    Export:
      Name: proy-datos-martin-solano-name

  # Export the ARN of the DataBucket
  DataBucketArn:
    Value: !GetAtt DataBucket.Arn
    Export:
      Name: proy-datos-martin-solano-arn

  # Output the name of the DynamoDB Table
  DynamoDBTableName:
    Value: !Ref DynamoDBTable
    Export:
      Name: proy-datospipeline-table-name

  # Exportar el Stream ARN
  DynamoDBStreamArn:
    Value: !GetAtt DynamoDBTable.StreamArn
    Export:
      Name: proy-datospipeline-table-stream-arn
